services:
  gateway:
    image: gateway:0.0.1
    ports:
      - 10001:10001
    container_name: gateway
    volumes:
      - ./gateway/gateway.jar:/app/gateway.jar
      - ./gateway/logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -sS http://localhost:10001/actuator/health ||exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2048M

  login:
    image: login:0.0.1
    ports:
      - 1111:80
    container_name: login
    volumes:
      - ./login/login:/apps
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -sS http://localhost:80 ||exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    image: nginx:1.27.5
    ports:
      - 10000:80
    container_name: nginx
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/http.conf:/etc/nginx/http.conf
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -sS http://localhost:80 ||exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
